// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiq_aOJIj4Jr6amFtBUu1b9xtTq15hPOU',
    appId: '1:1012769424316:web:81cf70d7e23f8792b461b9',
    messagingSenderId: '1012769424316',
    projectId: 'myexpensetracker-f9711',
    authDomain: 'myexpensetracker-f9711.firebaseapp.com',
    storageBucket: 'myexpensetracker-f9711.firebasestorage.app',
    measurementId: 'G-Q3SS8WX4TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj1GcXogjHV5lAmRPpb1_L6TJpPfnnq-o',
    appId: '1:1012769424316:android:8d00eb1228a0f4ecb461b9',
    messagingSenderId: '1012769424316',
    projectId: 'myexpensetracker-f9711',
    storageBucket: 'myexpensetracker-f9711.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWKoYgi6mBb7ro7viqyVaxD0vEFhqO6dg',
    appId: '1:1012769424316:ios:906eb735da15d0abb461b9',
    messagingSenderId: '1012769424316',
    projectId: 'myexpensetracker-f9711',
    storageBucket: 'myexpensetracker-f9711.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWKoYgi6mBb7ro7viqyVaxD0vEFhqO6dg',
    appId: '1:1012769424316:ios:906eb735da15d0abb461b9',
    messagingSenderId: '1012769424316',
    projectId: 'myexpensetracker-f9711',
    storageBucket: 'myexpensetracker-f9711.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiq_aOJIj4Jr6amFtBUu1b9xtTq15hPOU',
    appId: '1:1012769424316:web:0644e7f06621366cb461b9',
    messagingSenderId: '1012769424316',
    projectId: 'myexpensetracker-f9711',
    authDomain: 'myexpensetracker-f9711.firebaseapp.com',
    storageBucket: 'myexpensetracker-f9711.firebasestorage.app',
    measurementId: 'G-8Q3FCLYDB4',
  );
}
